# Generated by Django 4.2.2 on 2023-07-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('post_img', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 2, 0, 21, 12, 243251))),
            ],
        ),
    ]
