# Generated by Django 4.2.2 on 2023-07-02 10:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_caption_alter_posts_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 16, 2, 12, 676485)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45b65fd9-d843-40de-a58c-b2c6327d9ea0'), primary_key=True, serialize=False),
        ),
    ]
