# Generated by Django 5.2.8 on 2025-11-23 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_likepost_username_alter_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='username',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
