# Generated by Django 4.2.2 on 2023-07-02 14:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_likepost_alter_posts_created_at_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 28, 7, 828646)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa0ee956-8bfa-4493-99b9-79e227d8af82'), primary_key=True, serialize=False),
        ),
    ]
