# Generated by Django 4.2.2 on 2023-07-02 14:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_created_at_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 28, 18, 84325)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c4c5076-68ce-4058-a148-e3bbaa6e57f9'), primary_key=True, serialize=False),
        ),
    ]
