# Generated by Django 4.2.2 on 2023-07-02 14:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_created_at_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 39, 32, 123217)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6374e924-0505-47fa-bcc2-da8557e70ed4'), primary_key=True, serialize=False),
        ),
    ]
