# Generated by Django 4.2.2 on 2023-07-02 17:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_created_at_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 23, 25, 1, 643710)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0641a8ae-1332-437b-b820-db1e4f0f17b7'), primary_key=True, serialize=False),
        ),
    ]
