# Generated by Django 4.2.2 on 2023-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='blank-profile-photo.jpeg', upload_to='profile_images'),
        ),
    ]
